# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfSMeh4xoF6sCiSb4W0sHFdl6hIGcpyc
"""

#Import Libraries (Run First)
import numpy as np
import pandas as pd

#Experiment 1
#Create NumPy array, print shape & datatype

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

#Experiment 2
#Create matrices of zeros and ones

zeros_matrix = np.zeros((3,4))
ones_matrix = np.ones((2,5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

#Experiment 3
#Array 1–12 and reshape

arr = np.arange(1, 13)

reshaped_arr = arr.reshape(3,4)

print("Original Array:", arr)
print("Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped_arr)
print("Shape:", reshaped_arr.shape)

#Experiment 4
#Random integers + min, max, mean, sum

arr = np.random.randint(1, 100, 10)

print("Array:", arr)

print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())

#Experiment 5
#Create Pandas DataFrame

data = {
    "Name": ["Aman", "Riya", "Rahul", "Priya"],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)

print(df)

print("\nData Types:\n", df.dtypes)

#Experiment 6
#Read CSV + head() and tail()

df = pd.read_csv("/content/sample.csv")

print("First 5 rows:\n", df.head())

print("\nLast 5 rows:\n", df.tail())

#Experiment 7
#Dataset structure + missing values

print(df.info())

print("\nRows and Columns:", df.shape)

print("\nMissing Values:\n", df.isnull().sum())

#Experiment 8
#Statistical Summary

print(df.describe())